# Generated by Django 5.1.3 on 2024-12-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rooms_roomparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='chat_room_name',
            field=models.CharField(max_length=255),
        ),
    ]
